sudo: required

language: bash

services:
  - docker

script:
  - docker build -t bc-challenge-nginx .
  - docker run -d -p 8080:80 bc-challenge-nginx; sleep 10
  - docker ps | grep bc-challenge-nginx
  - curl -s -o /dev/null -I -w "%{http_code}" http://localhost:8080/ | grep 200
